services:
  udi-python:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Containerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        PYTHON39_VERSION_ARG: ${PYTHON39_VERSION_ARG}
        PYTHON312_VERSION_ARG: ${PYTHON312_VERSION_ARG}
        PYTHON313_VERSION_ARG: ${PYTHON313_VERSION_ARG}
        PYTHON314_VERSION_ARG: ${PYTHON314_VERSION_ARG}
        PYTHON_DEFAULT_MINOR_ARG: ${PYTHON_DEFAULT_MINOR_ARG}
    image: quay.io/${QUAY_ORG}/${IMAGE_NAME}:${IMAGE_TAG}
