services:
  udi-terraform:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Containerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        TFENV_VERSION_ARG: ${TFENV_VERSION_ARG}
        TERRAFORM_VERSIONS_ARG: ${TERRAFORM_VERSIONS_ARG}
        TERRAFORM_DEFAULT_ARG: ${TERRAFORM_DEFAULT_ARG}
        TFLINT_VERSION_ARG: ${TFLINT_VERSION_ARG}
        TERRAFORM_DOCS_VERSION_ARG: ${TERRAFORM_DOCS_VERSION_ARG}
        TERRATEST_VERSION_ARG: ${TERRATEST_VERSION_ARG}
        RANDOM_PROVIDER_VERSION_ARG: ${RANDOM_PROVIDER_VERSION_ARG}
        LOCAL_PROVIDER_VERSION_ARG: ${LOCAL_PROVIDER_VERSION_ARG}
    image: quay.io/${QUAY_ORG}/${IMAGE_NAME}:${IMAGE_TAG}
